version: '3'
services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start"
    volumes:
      - .:/qiitan
      - bundle:/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - db
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
